require 'rails_helper'
include Warden::Test::Helpers

feature 'User can register with an user that was autogenerated' do
  scenario 'a mod was created with an user in the #authors_list, then the author register with that name' do
    mod1 = create :mod, authors_list: 'Galaxy, Magenta', owner: nil, author: nil, name: 'PotatoMod'
    mod2 = build :mod, authors_list: 'Magenta', owner: nil, author: nil, name: "SaladMod"
    mod2.save!
    magenta = User.last
    expect(magenta.name).to eq 'Magenta'
    expect(magenta.autogenerated).to eq true
    visit '/users/register'
    fill_in 'user_email', with: 'apple@banana.com'
    fill_in 'user_name', with: 'Magenta'
    fill_in 'user_password', with: '12344321'
    fill_in 'user_password_confirmation', with: '12344321'
    click_button 'Register'
    magenta.reload
    expect(magenta.email).to eq 'apple@banana.com'
    expect(magenta.valid_password? '12344321').to eq true
    expect(magenta.autogenerated).to eq false
    expect(current_path).to eq '/users'
    expect(page).to have_content I18n.t('users.registrations.signed_up_autogenerated.mods_with_your_name')
    expect(page).to have_css 'a[href="http://www.factorioforums.com/forum/ucp.php?i=pm&mode=compose&u=1553"]'
    expect(page).to have_content /PotatoMod.*SaladMod/
    expect(page).to have_css 'a[href="/mods/potatomod"]'
    expect(page).to have_css 'a[href="/mods/saladmod"]'
  end
end