class AuthorsUsersSeparationUpdater
  def run
    User.all.each do |user|
      authors_mods = AuthorsMod.where(author_id: user.id)
      unless authors_mods.empty?
        author = Author.create! name: user.name, forum_name: user.name
        authors_mods.update_all(author_id: author.id)
        Author.reset_counters(author.id, :mods)
        if user.autogenerated?
          user.destroy!
        elsif author.mods.where(owner: user).count > 0
          author.user = user
          author.save!
        end
      end
    end
  end
end
