class AuthorsUsersSeparationUpdater
  def run
    User.all.each do |user|
      author = Author.create! name: user.name, forum_name: user.name
      AuthorsMod.where(author_id: user.id).update_all(author_id: author.id)
      if user.autogenerated?
        user.destroy!
      elsif author.mods.where(owner: user).count > 0
        author.user = user
        author.save!
      end
    end
  end
end
