User.create!(email: 'zequez@gmail.com', name: 'Zequez', password: 'qwfpqwfp', password_confirmation: 'qwfpqwfp', is_admin: true)

Category.create! name: 'Uncategorized',     icon_class: 'fa fa-question-circle'
Category.create! name: 'Sound',             icon_class: 'fa fa-headphones'
Category.create! name: 'Terrain',           icon_class: 'fa fa-globe'
Category.create! name: 'Campaigns',         icon_class: 'fa fa-flag'
Category.create! name: 'Gameplay',          icon_class: 'fa fa-gamepad'
Category.create! name: 'Equipment',         icon_class: 'fa fa-briefcase'
Category.create! name: 'Defense',           icon_class: 'fa fa-shield'
Category.create! name: 'Energy',            icon_class: 'fa fa-bolt'
Category.create! name: 'GUI',               icon_class: 'fa fa-desktop'
Category.create! name: 'Manufacturing',     icon_class: 'fa fa-cog'
Category.create! name: 'Weapons',           icon_class: 'fa fa-bomb'
Category.create! name: 'Transport Belts',   icon_class: 'fa fa-indent'
Category.create! name: 'Logistics Network', icon_class: 'fa fa-android'
Category.create! name: 'Oil',               icon_class: 'fa fa-tint'
Category.create! name: 'Resources',         icon_class: 'fa fa-cube'
Category.create! name: 'Textures',          icon_class: 'fa fa-picture-o'
Category.create! name: 'Containers',        icon_class: 'fa fa-archive'
Category.create! name: 'Vehicles',          icon_class: 'fa fa-automobile'
Category.create! name: 'Big Mods',          icon_class: 'fa fa-gears'
Category.create! name: 'Multiplayer',       icon_class: 'fa fa-group'
Category.create! name: 'Trains',            icon_class: 'fa fa-train'
Category.create! name: 'Science',           icon_class: 'fa fa-flask'
Category.create! name: 'Endgame',           icon_class: 'fa fa-rocket'
