User.create!(email: 'zequez@gmail.com', name: 'Zequez', password: 'qwfpqwfp', password_confirmation: 'qwfpqwfp', is_admin: true)

Category.create! name: 'Uncategorized',     icon_class: 'fa fa-question-circle'
Category.create! name: 'Sound',             icon_class: 'fa fa-headphones'
Category.create! name: 'Map',               icon_class: 'fa fa-globe'
Category.create! name: 'Campaigns',         icon_class: 'fa fa-flag'
Category.create! name: 'Gameplay',          icon_class: 'fa fa-gamepad'
Category.create! name: 'Equipment',         icon_class: 'fa fa-briefcase'
Category.create! name: 'Defense',           icon_class: 'fa fa-shield'
Category.create! name: 'Electricity',       icon_class: 'fa fa-bolt'
Category.create! name: 'GUI',               icon_class: 'fa fa-desktop'
Category.create! name: 'Manufacturing',     icon_class: 'fa fa-cog'
Category.create! name: 'Weapons',           icon_class: 'fa fa-crosshairs'
Category.create! name: 'Transport Belts',   icon_class: 'fa fa-indent'
Category.create! name: 'Logistics Network', icon_class: 'fa fa-android'
Category.create! name: 'Oil',               icon_class: 'fa fa-tint'
Category.create! name: 'Resources',         icon_class: 'fa fa-cube'
Category.create! name: 'Textures',          icon_class: 'fa fa-picture-o'
Category.create! name: 'Storage'   ,        icon_class: 'fa fa-archive'
Category.create! name: 'Vehicles',          icon_class: 'fa fa-automobile'
Category.create! name: 'Big Mods',          icon_class: 'fa fa-gears'
Category.create! name: 'Multiplayer',       icon_class: 'fa fa-group'
Category.create! name: 'Trains',            icon_class: 'fa fa-train'
Category.create! name: 'Science',           icon_class: 'fa fa-flask'
Category.create! name: 'Endgame',           icon_class: 'fa fa-rocket'
Category.create! name: 'Utilities',         icon_class: 'fa fa-wrench'
Category.create! name: 'Enemies',           icon_class: 'fa fa-paw'
Category.create! name: 'Environment',       icon_class: 'fa fa-tree'
Category.create! name: 'Turrets',           icon_class: 'fa fa-database'
Category.create! name: 'Buildings',         icon_class: 'fa fa-institution'
Category.create! name: 'Mining',            icon_class: 'fa fa-diamond'
Category.create! name: 'Inserters',         icon_class: 'fa fa-plug'
Category.create! name: 'Balance',           icon_class: 'fa fa-adjust'
Category.create! name: 'Warfare',           icon_class: 'fa fa-bomb'
Category.create! name: 'Transportation',    icon_class: 'fa fa-truck'
Category.create! name: 'Challenge',         icon_class: 'fa fa-trophy'
Category.create! name: 'Circuit Network',   icon_class: 'fa fa-power-off'
Category.create! name: 'Overhaul',          icon_class: 'fa fa-puzzle-piece'
Category.create! name: 'Liquids',           icon_class: 'fa fa-eyedropper'
Category.create! name: 'Player',            icon_class: 'fa fa-male'
Category.create! name: 'Devs',              icon_class: 'fa fa-code'
Category.create! name: 'Light',             icon_class: 'fa fa-lightbulb-o'
Category.create! name: 'Early game',        icon_class: 'fa fa-birthday-cake'