require 'securerandom'

class User < ActiveRecord::Base
  extend FriendlyId

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  friendly_id :name, use: [:slugged, :finders]

  has_many :mods, dependent: :nullify, foreign_key: :author_id
  has_many :authors_mods, dependent: :destroy, foreign_key: :author_id
  has_many :authored_mods, through: :authors_mods, class_name: 'Mod', source: :mod
  has_many :owned_mods, class_name: 'Mod', foreign_key: :author_id, dependent: :nullify # We'll change it to User#owner_id eventually

  def is_registered?
    !new_record?
  end

  def is_guest?
    new_record?
  end

  validates :name, presence: true,
                   format: { with: /\A[[:alnum:]\-_\. ]+\Z/i },
                   uniqueness: { case_sensitive: false },
                   length: { minimum: 2, maximum: 50 }

  before_validation do
    self.name = name.strip.squeeze(' ')
  end

  def self.autogenerate(attributes)
    attributes = attributes.reverse_merge(
      email: SecureRandom.hex(25) + '@' + SecureRandom.hex(25) + '.com',
      password: SecureRandom.hex(25),
      autogenerated: true
    )
    User.new attributes
  end

  # For validation
  def password_required?
    # We need to validate the password when the user
    # registers with previously autogenerated user
    super || (!autogenerated && autogenerated_was) 
  end
end
