describe Users::RegistrationsController, type: :controller do
  before :each do
    request.env['devise.mapping'] = Devise.mappings[:user]
  end

  describe 'POST create' do
    it 'should create a new user with valid parameters' do
      post :create, user: {
        email: 'potato@salad.com',
        name: 'Potato',
        password: '12345678',
        password_confirmation: '12345678'
      }
      user = User.first
      expect(user.email).to eq 'potato@salad.com'
      expect(user.name).to eq 'Potato'
    end

    it 'should add errors to the user with invalid parameters' do
      post :create, user: {
        email: 'potatosalad.com',
        name: '',
        password: '1278',
        password_confirmation: '12345678'
      }
      expect(User.all).to be_empty
      user = assigns(:user)
      expect(user.errors[:email]).to_not be_empty
      expect(user.errors[:name]).to_not be_empty
      expect(user.errors[:password]).to_not be_empty
      expect(user.errors[:password_confirmation]).to_not be_empty
    end

    context 'the user was autogenerated' do
      it 'should use the same user and replace the email and password' do
        user = create :user,
          name: 'Potato',
          email: 'potato@salad.com',
          password: 'rsarsarsa',
          autogenerated: true
        post :create, user: {
          name: 'Potato',
          email: 'potato2@salad.com',
          password: '12345678'
        }
        user.reload
        expect(assigns(:user)).to eq user
        expect(user.name).to eq 'Potato'
        expect(user.email).to eq 'potato2@salad.com'
        expect(user.valid_password?('12345678')).to eq true
        expect(user.autogenerated).to eq false
      end
    end
  end
end
