# https://github.com/plataformatec/devise/blob/master/app/controllers/devise/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def create
    @user = User.where(autogenerated: true).where('lower(name) = ?', sign_up_params[:name].downcase).first
    if @user
      @user.email = nil
      @user.password = nil
      @user.assign_attributes(sign_up_params)
      @user.autogenerated = false
      self.resource = @user
      if @user.save
        sign_up(:user, @user)
        render :signed_up_autogenerated
      else
        clean_up_passwords @user
        set_minimum_password_length
        respond_with @user
      end
    else
      super # Continue with regular registration
    end
  end
end
